### ISSUE TITLE
fatal error C1083: Cannot open include file: 'VersionRev.h'

### ISSUE THREAD

**Issue by sarangbaheti** [XhmikosR/notepad2-mod#102]
Hi 

Is there any other build dependency for this project?
I cloned the repository and built the VS2012.sln/make_all_vs2013.bat/build_vs2013.bat

it fails with error:

  Scintilla.vcxproj -> D:\oss\notepad2-mod\scintilla..\bin\VS2013\Release_x86\obj\scintilla\Scintilla.lib
  ./version.sh: [[: command not found
  ./version.sh: version_info+=#define VERSION_HASH _T("2e039e9")$\n: command not found
  ./version.sh: version_info+=#define VERSION_REV 938$\n: command not found
  ./version.sh: version_info+=#define VERSION_REV_FULL _T("938 (2e039e9)"): command not found
  ./version.sh: [[: command not found
  Hash:      2e039e9
  ./version.sh: [[: command not found
  Revision:  938
  ./version.sh: [[: command not found
  ./version.sh: [[: command not found
  ./version.sh: ./src/VersionRev.h: No such file or directory
  ./version.sh: [[: command not found
  ./version.sh: [[: command not found
  ./version.sh: ./res/Notepad2.exe.manifest: No such file or directory
  ./version.sh: [[: command not found
  Dialogs.c
d:\oss\notepad2-mod\src\version.h(19): fatal error C1083: Cannot open include file: 'VersionRev.h': No such file or dir
ectory [d:\oss\notepad2-mod\src\Notepad2.vcxproj]

---

[ERROR] Compilation failed!

---

Press any key to continue . . .

**Comment by Runcy** [comment]
You can try to chang the file's Character Encoding.

**Comment by XhmikosR** [comment]
@Runcy: Completely irrelevant...

**Comment by rorgoroth** [comment]
For what it's worth git for windows (v2.x.x+) uses msys2, so you can use the git bash shell to run version.sh  which makes this issue a lot less of one.
