### ISSUE TITLE
Exception running in VS2013 64bit when opening scheme dialog

### ISSUE THREAD

**Issue by mikagenic** [XhmikosR/notepad2-mod#109]
To reproduce simply open the solution in VS2013, change to x64, build, run, press F12

I get 'Notepad2.exe has trigerred a breakpoint'

If I click Break it stops in ntdll.dll
If I continue it seems to work fine but not sure.

This happens in x64 debug & release but not in x32 debug or release

**Comment by XhmikosR** [comment]
I'm aware of this, but I couldn't figure out why this happened.
PR is welcomed.

**Comment by Vitallium** [comment]
It's ok. F12 causes the debuggee to break when the app has focus. You can read more here: https://support.microsoft.com/en-us/kb/130667

**Comment by XhmikosR** [comment]
Duh, indeed, thanks!
