### ISSUE TITLE
VS2010: error : Element <EnableEnhancedInstructionSet> has an invalid value of “NoExtensions”

### ISSUE THREAD

**Issue by oezgueremir** [XhmikosR/notepad2-mod#111]
_ This post is meant to help future users compiling this project _

I don't know, if I am the only who had this problem, but the (my) VS2010 Compiler does not support the predefined value "NoExtensions" for the "Enable Enhanced Instruction Set" configuration in Notepad2.vcxproj and Scintilla.vcxproj. This value seems to be a valid VS2012 constant.

The fix[*] was done by replacing this line
```
      <EnableEnhancedInstructionSet>NoExtensions</EnableEnhancedInstructionSet>
```
with this
```
      <EnableEnhancedInstructionSet>NotSet</EnableEnhancedInstructionSet>
```
in all corresponding files.

[*]found on: https://stackoverflow.com/questions/23339260/error-element-enableenhancedinstructionset-has-an-invalid-value-of-noextens

Btw the old "Notepad2_VS2010.vcxproj" did not have any "EnableEnhancedInstructionSet" entries...

**Comment by XhmikosR** [comment]
I do not use VS2010. The fix is easy but just upgrade your compiler regardless.

**Comment by XhmikosR** [comment]
Should be fixed in https://github.com/XhmikosR/notepad2-mod/commit/43284c99059ccec6c9dfd75a30ac3fdd3de6eb3e.
