### ISSUE TITLE
Leading stretched vertically

### ISSUE THREAD

**Issue by MarekK82** [XhmikosR/notepad2-mod#113]
In the default scheme the **leading** between the lines seems to be stretched vertically compared to the *2nd Default Scheme*. Is this wanted that way? Or is there a way one can adjust the leading?

**Comment by Phanx** [comment]
* Customize Schemes > Default Text > Extra Line Spacing (Size)
* Customize Schemes > Default Text > 2nd Extra Line Spacing (Size)

**Comment by MarekK82** [comment]
Nice one, I wasn't expecting that setting exists :-O Thank you very much!
