### ISSUE TITLE
Implementing export to RTF/PDF/HTML

### ISSUE THREAD

**Issue by mikagenic** [XhmikosR/notepad2-mod#114]
I implemented export to RTF/PDF/HTML on the existing codebase and want to see if there is interest in committing it.

I created a supporting environment which allows compiling of exporters.cxx from the SciTE codebase and calling the relevant functions. I could not get syntax coloring to work so everything is exported as plain text, however the infrastructure is there so maybe I can collaborate with someone more knowledgeable on that.

~~You can try the executable here 
See Export from the File menu~~

Please let me know what you think

**Comment by Dragonji** [comment]
You could post your code instead of attaching unknown binaries.

**Comment by XhmikosR** [comment]
Please don't post random binaries. Make pull requests instead.
