### ISSUE TITLE
Line Numbers be not well if use an other but correct ttf.

### ISSUE THREAD

**Issue by blackcrack** [XhmikosR/notepad2-mod#118]
Hi,

i use this TTF : 
https://jira.reactos.org/browse/CORE-7706
The Original Page : 
http://www.inp.nsk.su/~bolkhov/files/fonts/univga/

and the Line numbers be not correctly represented/shown

best regards
Blacky

**Comment by XhmikosR** [comment]
No idea what the problem is or why it fails.

See if it happens with vanilla Notepad2.

**Comment by blackcrack** [comment]
i install the ttf, go under view -> standardfont , change the font to vga one and the left sided Fonts be the size smaller and therewith fits not correctly . because the sitze is an bit smaller as should be.
If i set up the Standartfont to 12px , it is the sitz of the linenumbers 11px and therewith it is not correctly displayed . the linenumbers should be able for setting up as own config size or an other font with an own size .

best regards
Blacky

**Comment by gwarser** [comment]
View -> Customize Schemes... -> double click on "Default Text" -> Margins and Line Numbers

**Comment by XhmikosR** [comment]
Sorry, I'm not going to install a random font.

Like I said, check what happens with Notepad2.

**Comment by blackcrack** [comment]
notepad2 it is the size of font on the line numbers a size too small and does not display correctly .

best
Blacky
