### ISSUE TITLE
Ctrl+Shift+0 (Show wrap symbols) does not toggle

### ISSUE THREAD

**Issue by Rikk** [XhmikosR/notepad2-mod#120]
First time looking at this light editor...
It seems that the Ctrl+Shift+0 (Show wrap symbols) shortcut does not toggle the option. Can enable it only via menu.
Ctrl+Shift+8 and Ctrl+Shift+9 both works.

**Comment by XhmikosR** [comment]
Indeed, confirmed.

Does it happen with vanilla Notepad2? I don't recall touching that code at all, but it might be a typo that broke it somewhere along the way.

**Comment by Rikk** [comment]
> Does it happen with vanilla Notepad2?
Yes, both in 4.2.25 and 5.0.26beta

**Comment by bluenlive** [comment]
Windows IME causes this problem.

https://support.microsoft.com/en-us/kb/967893

**Comment by Rikk** [comment]
>Windows IME causes this problem.
https://support.microsoft.com/en-us/kb/967893

Exact! You solved the mystery.

@XhmikosR, perhaps a new shortcut would be better? I'd suggest reduce by one these Ctrl+Shift numbers (7,8,9 instead of 8,9,0), if there's no conflict.
