### ISSUE TITLE
TypeScript Scheme

### ISSUE THREAD

**Issue by GoToLoop** [XhmikosR/notepad2-mod#128]
Is there any future plan to include some TypeScript scheme for Notepad2-mod?

**Comment by QWp6t** [comment]
It's not available upstream, and it doesn't look like they're interested in implementing it themselves.

http://sourceforge.net/p/scintilla/feature-requests/958/

You could try submitting a patch upstream.

**Comment by GoToLoop** [comment]
Oh well. Dunno how to make schemes. At least they're already aware of that. Thx!
