### ISSUE TITLE
hope can add i18n ui

### ISSUE THREAD

**Issue by bluelovers** [XhmikosR/notepad2-mod#144]
hope can add i18n ui

 i use Sisulizer for make it has chinese lang at long time before

but today it not work on new notepad2-mod

**Comment by XhmikosR** [comment]
Sorry, not interested in any localization.

**Comment by bluelovers** [comment]
i mean add option or loading ini, let user can add lang if he want

**Comment by blackcrack** [comment]
nope.. no way, either you translate it via brunch for translate ..
or nothing.. XhmikosR it's the owner here and i mus stay behind him..and he have closed it !! 
if you not understand this, it's your problem .. but nerve not !
this issue it is closed !

best regards
Blacky
