### ISSUE TITLE
Inner license

### ISSUE THREAD

**Issue by mikeyhalla** [XhmikosR/notepad2-mod#147]
You have: MPC-HC is free software;
in your license file area. In your version.sh to be specific...

Just letting you know!

Thank you for keeping this alive as I prefer it over notepad++

**Comment by joedf** [comment]
Yup, good catch! :+1: 
3 occurrences here: https://github.com/XhmikosR/notepad2-mod/blob/master/version.sh#L4-L11

**Comment by XhmikosR** [comment]
This is by design. I'm the author of that file and I used it here too.
