### ISSUE TITLE
Messy syntax highlighting in comments of .inc files (php).

### ISSUE THREAD

**Issue by klonos** [XhmikosR/notepad2-mod#149]
File in question: https://raw.githubusercontent.com/backdrop/backdrop/1.x/core/includes/ajax.inc

![notepad2-mod-messy_syntax_highlighting-inc_files_php-1](https://cloud.githubusercontent.com/assets/2423362/13214723/74b66fae-d9a5-11e5-8f4f-4f75992c3e25.png)
![notepad2-mod-messy_syntax_highlighting-inc_files_php-2](https://cloud.githubusercontent.com/assets/2423362/13214724/74ba4fa2-d9a5-11e5-8d44-1069cc7a9d73.png)
![notepad2-mod-messy_syntax_highlighting-inc_files_php-3](https://cloud.githubusercontent.com/assets/2423362/13214725/74c1acf2-d9a5-11e5-9db2-47b92b1055a9.png)
![notepad2-mod-messy_syntax_highlighting-inc_files_php-4](https://cloud.githubusercontent.com/assets/2423362/13214726/74cf4b8c-d9a5-11e5-8867-7c0ef64e94f7.png)

**Comment by XhmikosR** [comment]
This is by design because .inc files are set to be detected as pascal files.
Just change your settings.

**Comment by klonos** [comment]
That did it, thanx!
