### ISSUE TITLE
Transfer ownership of the Chocolatey package

### ISSUE THREAD

**Issue by AnthonyMastrean** [XhmikosR/notepad2-mod#152]
I am one of the maintainers of the notepad2-mod package on Chocolatey, a Windows package manager. This is a _very_ popular package. Would you be willing to take over maintenance/ownership of the package to improve the timeliness of updates?

I'm willing to provide any documentation, training, or just a PR. Whatever helps!

https://chocolatey.org/packages/notepad2-mod

**Comment by XhmikosR** [comment]
Sorry, I don't use this myself. If you could update it yourself that would
be the best.

**Comment by QWp6t** [comment]
@AnthonyMastrean you can use a service like [Sibbell](https://sibbell.com/) (free) to be notified by email when a new release is published.

**Comment by AnthonyMastrean** [comment]
There are some automatic package update procedures that I haven't quite figured out yet.

https://chocolatey.org/docs/automatic-packages
