### ISSUE TITLE
Notepad2-mod uses single instance mode on Win10

### ISSUE THREAD

**Issue by DMcCunney** [XhmikosR/notepad2-mod#157]
I recently upgraded to Win10.  Notepad2-mod works fine, save that invoking it always opens an existing instance, as though Single File Instance was checked in settings.  It does that whether that setting is checked or not.  Since I often need more than one instance open, this is a problem.

Has anyone else seen this, or know of a simple fix?

**Comment by zufuliu** [comment]
uncheck Settings -> Reuse Window

**Comment by DMcCunney** [comment]
It _is_ unchecked, which prompted the report.

The problem has subsequently gone away, and Notepad2 behaves as expected.  I was experieneing weird quirks in Win10 Pro, and this was one of them.
