### ISSUE TITLE
fatal: Invalid revision range 

### ISSUE THREAD

**Issue by kuh3h3** [XhmikosR/notepad2-mod#158]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>d:

D:\>cd note*

D:\notepad2-mod>dir
 D 드라이브의 볼륨: data
 볼륨 일련 번호: 54EC-8AD5

 D:\notepad2-mod 디렉터리

2016-05-19  오전 06:02    <DIR>          .
2016-05-19  오전 06:02    <DIR>          ..
2016-05-19  오전 05:58                16 .gitattributes
2016-05-19  오전 05:58               326 .gitignore
2016-05-19  오전 06:02    <DIR>          bin
2016-05-19  오전 05:58    <DIR>          build
2016-05-19  오전 05:58    <DIR>          distrib
2016-05-19  오전 05:58             1,159 lexlink.js
2016-05-19  오전 05:58             1,591 License.txt
2016-05-19  오전 05:58            23,392 Notepad2.ini
2016-05-19  오전 05:58            39,728 Notepad2.txt
2016-05-19  오전 05:58             1,416 Readme-mod.txt
2016-05-19  오전 05:58             1,912 Readme.md
2016-05-19  오전 05:58             3,147 Readme.txt
2016-05-19  오전 05:58    <DIR>          res
2016-05-19  오전 05:58    <DIR>          scintilla
2016-05-19  오전 06:00    <DIR>          src
2016-05-19  오전 06:00               534 update_rev.bat
2016-05-19  오전 05:58               516 update_rev.bat.bak
2016-05-19  오전 05:58             3,297 version.sh
              12개 파일              77,034 바이트
               8개 디렉터리  12,790,091,776 바이트 남음

D:\notepad2-mod>update_rev
fatal: Invalid revision range 0cd53aab71b006820233224bbf14c2b18b2caca6..HEAD
On branch: master
Hash:      5e7c586
Revision:  760 (Local modifications found)

D:\notepad2-mod>git log
commit 5e7c5866ec65a195e2c6648ec01769c29c14f8fc
Author: XhmikosR <xhmikosr@gmail.com>
Date:   Tue May 3 19:25:03 2016 +0300

    Add MSVC 2015 Update 2 version number.

D:\notepad2-mod>

**Comment by XhmikosR** [comment]
Bash is required for version.sh.

**Comment by kuh3h3** [comment]
closed this issue ? maybe you thought that is simple.
i installed and  added  MSYS PATH in update_rev.bat
SET "MSYS=D:\MSYS"
SET PATH=%MSYS%\bin;%PATH%

so update_rev.bat  could run bash and could run version.sh on vs 2015 command prompt.

you mean i have to go first  Msys bash?
then if go to C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC,
and run vcvarsall.bat?

that mot work at all.

**Comment by XhmikosR** [comment]
Sorry, if you want to learn how to handle PATH in scripts, this is certainly not my job.

If you want to submit a PR to get rid of the MSYS requirement, go ahead.

This is an old solution I used when I switched to Git from SVN. I never got the time or the interest to change this since it works for me.

**Comment by kuh3h3** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>d:
D:\>cd note*
D:\notepad2-mod>git --version
git version 2.8.2.windows.1

D:\notepad2-mod>git pull
Already up-to-date.
D:\notepad2-mod>update_rev
fatal: Invalid revision range 0cd53aab71b006820233224bbf14c2b18b2caca6..HEAD
On branch: master
Hash:      5e7c586
Revision:  760 (Local modifications found)

D:\notepad2-mod>bash version.sh
fatal: Invalid revision range 0cd53aab71b006820233224bbf14c2b18b2caca6..HEAD
On branch: master
Hash:      5e7c586
Revision:  760 (Local modifications found)

D:\notepad2-mod>git symbolic-ref -q HEAD
refs/heads/master

D:\notepad2-mod>git merge-base master HEAD
5e7c5866ec65a195e2c6648ec01769c29c14f8fc

D:\notepad2-mod>git rev-list --count 0cd53aab71b006820233224bbf14c2b18b2caca6..5e7c5866ec65a195e2c6648ec01769c29c14f8fc
fatal: Invalid revision range 0cd53aab71b006820233224bbf14c2b18b2caca6..5e7c5866ec65a195e2c6648ec01769c29c14f8fc

D:\notepad2-mod>git rev-list --count 0cd53aab71b006820233224bbf14c2b18b2caca6..HEAD
fatal: Invalid revision range 0cd53aab71b006820233224bbf14c2b18b2caca6..HEAD

D:\notepad2-mod>git rev-parse --short HEAD
5e7c586

**Comment by kuh3h3** [comment]
sorry. my problem is clone depth.
git clone --depth 1 caused all this error.
after full clone, all is ok
