### ISSUE TITLE
make_zip.bat fail - 7za wasn't found!

### ISSUE THREAD

**Issue by rexx** [XhmikosR/notepad2-mod#163]
Hi,
I have a problem running the make zip, it says 7za was not found.
I look into the script, in the subroutine SubDetectSevenzipPath, I removed the following two line and then it works for me.
`rem FOR %%G IN (7za.exe) DO (SET "SEVENZIP_PATH=%%~$PATH:G")`
`rem IF EXIST "%SEVENZIP_PATH%" (SET "SEVENZIP=%SEVENZIP_PATH%" & EXIT /B)`
I'm using 7-zip 9.20 and I don't have 7za.exe in C:\Program Files\7-Zip, there's only 7z.exe
I'm not sure why it won't fall to use registry way to detect the path, but after removing the above lines, it just works.

**Comment by rexx** [comment]
After updating to 7-zip 16.02, it works now..

**Comment by XhmikosR** [comment]
It's your environment that lacked the needed registry keys anyway.
