### ISSUE TITLE
Shipped along with another app

### ISSUE THREAD

**Issue by polyvertex** [XhmikosR/notepad2-mod#167]
Hi, not an issue or a request but I could not find how else I could contact you.

In case you care, I just wanted to notify you about an other use of your fork: [Keypirinha](http://keypirinha.com) (I'm the author). More specifically, Notepad2-mod is shipped with Keypirinha since a lightweight text editor was required to offer the ability to the user to edit config files out of the box.

Since Keypirinha is not open sourced, please let me know if you have any concern about the way Notepad2-mod is used here.

Cheers

**Comment by XhmikosR** [comment]
My email is visible in my profile but anyway.

As long as you follow the license there should be no issue. So make sure you understand the license.

**Comment by polyvertex** [comment]
Sorry for the e-mail, I saw it only after having opened the issue.
I've read the license, it was more out of courtesy and as a thank you for your Notepad2 fork.
