### ISSUE TITLE
main tag in web source code

### ISSUE THREAD

**Issue by syshut** [XhmikosR/notepad2-mod#169]
html5 \<main\> tag will be displayed as highlighted, which means an unknown tag name. could this be fixed?

**Comment by XhmikosR** [comment]
No idea what you're talking about.

**Comment by klonos** [comment]
![notepad2-mod-issue169](https://cloud.githubusercontent.com/assets/2423362/18128542/a8a6dee2-6fc9-11e6-8c37-d0a2a6e99cf2.png)

**Comment by XhmikosR** [comment]
You can submit a PR.

The HTML keywords are pretty old.

**Comment by XhmikosR** [comment]
OK this was easy, it was a bug. Fixed in https://github.com/XhmikosR/notepad2-mod/commit/b85dab70ddded3e3b0691c6da9371c03eeff15b6

**Comment by syshut** [comment]
thanks for your job, there are also 2 tag properties named "itemscope" and "itemtype"

**Comment by syshut** [comment]
![srcset](https://cloud.githubusercontent.com/assets/21360506/18208462/2a27a00c-7162-11e6-882a-19e2dc2c57a7.png)

**Comment by syshut** [comment]
thanks for the work! please also add the srcset attribute for the img tag

**Comment by XhmikosR** [comment]
@syshut: please make a new issue with the full list of keywords missing.

**Comment by syshut** [comment]
@XhmikosR sorry but i really can not help with that.
i found this bug because i'm a wordpress user and sometimes i use this notepad tool to read the php code, so i could only find some certain mis-highlighted attributes.
but i'm not a developer, and i do not have the whole html tag attributes (or say, the keywords) list.
i really want to help, and i tried to search but i found no good result.
thanks again for your job.
