### ISSUE TITLE
ANSI don't show characters with punctuation

### ISSUE THREAD

**Issue by mtrakal** [XhmikosR/notepad2-mod#180]
I have ANSI encoding, when I insert character `č` it is represent as: `c` in notepad2-mod. But in previous version of notepad2-mod it shown as `č`. In default windows-1250 encoding which is set for my Windows.

I set default encoding to UTF-8 and everything is ok now, but it's scary, that I write one character and it's shown different character :)

Windows 10 x64, notepad2-mod: 4.2.25 r985 (7529a6b)

**Comment by XhmikosR** [comment]
See https://github.com/XhmikosR/notepad2-mod/issues/173
