### ISSUE TITLE
Include the browser plugin metapath in the installer of Notepad2-mod

### ISSUE THREAD

**Issue by smed79** [XhmikosR/notepad2-mod#186]
Hi, 

can you please include the default browser plugin "[metapath.exe](http://www.flos-freeware.ch/archive.html)" in the installer of Notepad2-mod.

Thank you.

**Comment by zufuliu** [comment]
Notepad2-mod is Incompatible with metapath, see issue https://github.com/XhmikosR/notepad2-mod/issues/123 on how to solve.

**Comment by smed79** [comment]
Already
