### ISSUE TITLE
Delphi $REGION prevents code folding

### ISSUE THREAD

**Issue by ShadyGaDa** [XhmikosR/notepad2-mod#189]
newer delphi regioning...
{$REGION 'some comment'}
//uncollapsable procedures / functions
begin
    if a then
    begin
      if b == c then
      begin
        d := e;
        f :=g;
      end;
    end;
end
{$ENDREGION  'some comment'}
Had a hack around with it but scintilla is a beast.

**Comment by XhmikosR** [comment]
Upstream issue.
