### ISSUE TITLE
add ESC-key pressing for closing and ask for save

### ISSUE THREAD

**Issue by blackcrack** [XhmikosR/notepad2-mod#192]
hi,

can you maybe add add ESC-key-pressing for closing and ask for save

best regards
Blacky

**Comment by coreequip** [comment]
`Settings -> Esc Key Function -> Exit Notepad2-mod`:

![image](https://user-images.githubusercontent.com/1869598/26876552-0dfe089e-4b87-11e7-8b27-dd773854fd9b.png)

Is it not what you are looking for?

**Comment by blackcrack** [comment]
oh cool !
thy, can closed :)

best regards
blacky
