### ISSUE TITLE
Turkish character problem in new versions.

### ISSUE THREAD

**Issue by zembereck** [XhmikosR/notepad2-mod#195]
Hello, new versions no longer support Turkish characters (ı, ö, ç, ğ, ü). 

For example; 
When I type in "ı" letter, notepad2 is writing as "i"

There is no problem in the 4.2.25.980 version. There is problem with versions after 4.2.25.980 version.

Thanks.

**Comment by efotinis** [comment]
I have a similar problem in various Win7 installs with a Greek system locale. Typing or pasting the whole alphabet in an ANSI document produces "aß?de??????µ???p?st?f???", which looks like a mapping to a wrong encoding. Temporarily switching the document to a Unicode encoding (UTF8/16) for editing and then back to ANSI for saving fixes the problem, but that of course is not a viable solution.
