### ISSUE TITLE
Better wrapping for long links

### ISSUE THREAD

**Issue by john-cj** [XhmikosR/notepad2-mod#224]
Here is what I mean:

Here are six hyperlinks in comments of my code:

![notepad2_1](https://user-images.githubusercontent.com/18004961/42737985-dafc6e18-8884-11e8-986b-e83d53bf7318.JPG)

When editor window is not wide enough, long links are moved entirely to the new visual line, instead of being properly wrapped:

![notepad2_2](https://user-images.githubusercontent.com/18004961/42737988-e1f19400-8884-11e8-8581-52dc70cc631a.JPG)

Desired behaviour:

![desired](https://user-images.githubusercontent.com/18004961/42737992-e70b3c0c-8884-11e8-8f4e-2919d22b64aa.JPG)

**Comment by zufuliu** [comment]
It's a upstream Scintilla bug, I created a ticket at https://sourceforge.net/p/scintilla/feature-requests/1223/.

**Comment by john-cj** [comment]
@zufuliu Thanks!

**Comment by john-cj** [comment]
@zufuliu His motivation is very strange. What is the problem for lisp variable to be wrapped? Also, if he don't like to implement soft-wrapping on hyphens, well, it could be wrapped on slashes! `/`

```
; http://site.com/foo-bar-baz/
aaa_bbb_ccc.html
```

is better then

```
;
http://site.com/foo-bar-baz/
aaa_bbb_ccc.html
```

**Comment by zufuliu** [comment]
@john-cj indeed, so I suggest you reopen this bug, the ticket in Scintilla is not yet closed.
