### ISSUE TITLE
Create or open new file without closing old one?

### ISSUE THREAD

**Issue by john-cj** [XhmikosR/notepad2-mod#225]
I know, there is an option "Single File Instance" available under "Settings" in the menu.

However, it seems it doesn't work. Try to disable this option and then perform these two tests:

1. Open some file with Notepad2-mod, then press Ctrl-N. You will see that the new file was created in the same window. So, now you have blank new file, but you lost the previous one. (Desired behaviour: New file should be created in a new window. Old window should stay).

2. Open some file with Notepad2-mod, then press Ctrl-O and then select another file to open. You will see that the new file was opened in the same window. So, now you have second file opened, but you lost  the previous one. (Desired behaviour: Second file should be opened in a new window. Old window should stay).

So, is it a bug?

**Comment by zufuliu** [comment]
"Single File Instance" is deigned as that when open the same file multiply times, the file will not open in multiply Notepad2 window, only one.

1. For <kbd>Ctrl</kbd>+<kbd>N</kbd>, maybe it's better to open an empty window  (<kbd>Alt</kbd>+<kbd>0</kbd>, File -> Launch -> Empty Window) when current window is not empty.

**Comment by john-cj** [comment]
@zufuliu Thanks. This method also works for Ctrl-O. (Open some file, then press Alt-0 and then press Ctrl-O in a new window).
