### ISSUE TITLE
Add CoffeeScript support

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/notepad2-mod#51]

**Comment by henrypijames** [comment]
Any progress here? The CoffeeScript branch has vanished, is that good or bad?

**Comment by XhmikosR** [comment]
The branch is there but no progress. #52

**Comment by henrypijames** [comment]
What's needed to make progress?
And isn't it possible to offer CoffeeScript support to the same degree Scintilla does, for now?

**Comment by XhmikosR** [comment]
Well, I'm not sure about the styles I have used and if they cover all cases.

Anyway, this discussion should be make there.
